sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAYCsVLwS9rHA2dUQfP
    access-key-secret: 3sh8Tye6ZD443QsfBSz46PCssrRiFI
    bucket-name: web-zq-ski